export const dqqQuestions = [
  ["section", "Categories that should be consumed"],
  [
    "DQQ1",
    "Foods made from grains (like maize, rice, wheat, bread, pasta, porridge)",
  ],
  [
    "DQQ2",
    "Whole grains (like brown rice, whole wheat bread, whole grain cereal)",
  ],
  [
    "DQQ3",
    "White roots or tubers (like potatoes, yams, cassava, manioc - not orange inside)",
  ],
  ["divider"],
  ["DQQ4", "Pulses (beans, peas, lentils)"],
  ["divider"],
  [
    "DQQ5",
    "Vitamin A-rich orange vegetables (like carrots, pumpkin, orange sweet potatoes)",
  ],
  ["DQQ8", "Vitamin A-rich fruits (like ripe mangoes, papayas)"],
  ["divider"],
  ["DQQ6", "Dark green leafy vegetables (like spinach, kale, local greens)"],
  ["divider"],
  ["DQQ7", "Other vegetables (like tomatoes, onions, eggplant)"],
  ["divider"],
  ["DQQ9", "Citrus fruits (like oranges, lemons, tangerines)"],
  ["DQQ10", "Other fruits (like apples, bananas, grapes)"],
  ["divider"],
  ["DQQ13", "Eggs"],
  ["divider"],
  ["DQQ14", "Cheese"],
  ["DQQ15", "Yogurt (including yogurt drinks)"],
  ["DQQ25", "Milk (fluid milk, powdered milk reconstituted)"],
  ["divider"],
  ["DQQ16", "Processed meats (like sausages, hot dogs, salami, canned meat)"],
  ["DQQ17", "Unprocessed red meat (ruminant - beef, lamb, goat)"],
  ["DQQ18", "Unprocessed red meat (non-ruminant - pork)"],
  ["DQQ19", "Poultry (chicken, turkey, duck)"],
  ["DQQ20", "Fish or seafood"],
  ["divider"],
  ["DQQ21", "Nuts or seeds"],
  ["divider"],
  ["section", "Categories that should be avoided"],
  [
    "DQQ11",
    "Baked or grain-based sweets (like cakes, cookies, pastries, sweet biscuits)",
  ],
  ["divider"],
  ["DQQ12", "Other sweets (like chocolate, candies, sugar)"],
  ["divider"],
  ["DQQ22", "Packaged ultra-processed salty snacks (like chips, crisps)"],
  ["divider"],
  ["DQQ23", "Instant noodles"],
  ["divider"],
  ["DQQ24", "Deep fried foods (from restaurants or street vendors)"],
  ["divider"],
  ["DQQ26", "Sweet tea, coffee, or cocoa (with sugar added)"],
  ["divider"],
  ["DQQ27", "Fruit juice or fruit drinks (packaged or freshly made)"],
  ["divider"],
  ["DQQ28", "Soft drinks, energy drinks, or sports drinks"],
  ["divider"],
  ["DQQ29", "Fast food (purchased from fast-food outlets)"],
];
